# Site settings
name: Giselle
email: gisellet6387@hstat.org
url: url
description: "A blog and a portfolio"
author: "Giselle"
title: "BlogFolio"
permalink: pretty
baseurl: /jekyll-theme-blogfolio

# social
github:
  username: gisellet6387

twitter:
  username: username